// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package token

import (
	"blog/api/token"
)

type ControllerV1 struct{}

func NewV1() token.ITokenV1 {
	return &ControllerV1{}
}
