// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package test

import (
	"blog/api/test"
)

type ControllerV1 struct{}

func NewV1() test.ITestV1 {
	return &ControllerV1{}
}
