// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package rbac

import (
	"blog/api/rbac"
)

type ControllerV1 struct{}

func NewV1() rbac.IRbacV1 {
	return &ControllerV1{}
}
