// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// internalManyRolePermissionDao is internal type for wrapping internal DAO implements.
type internalManyRolePermissionDao = *internal.ManyRolePermissionDao

// manyRolePermissionDao is the data access object for table many_role_permission.
// You can define custom methods on it to extend its functionality as you wish.
type manyRolePermissionDao struct {
	internalManyRolePermissionDao
}

var (
	// ManyRolePermission is globally public accessible object for table many_role_permission operations.
	ManyRolePermission = manyRolePermissionDao{
		internal.NewManyRolePermissionDao(),
	}
)

// Fill with you ideas below.
