// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// internalPermissionReadDao is internal type for wrapping internal DAO implements.
type internalPermissionReadDao = *internal.PermissionReadDao

// permissionReadDao is the data access object for table permission_read.
// You can define custom methods on it to extend its functionality as you wish.
type permissionReadDao struct {
	internalPermissionReadDao
}

var (
	// PermissionRead is globally public accessible object for table permission_read operations.
	PermissionRead = permissionReadDao{
		internal.NewPermissionReadDao(),
	}
)

// Fill with you ideas below.
