// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// internalPermissionMenuDao is internal type for wrapping internal DAO implements.
type internalPermissionMenuDao = *internal.PermissionMenuDao

// permissionMenuDao is the data access object for table permission_menu.
// You can define custom methods on it to extend its functionality as you wish.
type permissionMenuDao struct {
	internalPermissionMenuDao
}

var (
	// PermissionMenu is globally public accessible object for table permission_menu operations.
	PermissionMenu = permissionMenuDao{
		internal.NewPermissionMenuDao(),
	}
)

// Fill with you ideas below.
